apiVersion: v1
kind: Service
metadata:
  name: neuroclima-client-nodeport
  namespace: uoulu
  labels:
    app: neuroclima
    component: client
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30180  # Access your app at http://<node-ip>:30180
    protocol: TCP
    name: http
  selector:
    app: neuroclima
    component: client
